
server:
  port: 8000

spring:
  profiles.active: local
  application:
    name: smartcity-api
  jackson:
    default-property-inclusion: NON_NULL

  #  datasource.url: jdbc:postgresql://175.113.135.40:6319/?useUnicode=yes&characterEncoding=UTF-8
  #  datasource.username: smartcity
  #  datasource.password: smartcity64181!
  #  datasource.testOnBorrow: true
  #  datasource.validationQuery: SELECT 1

  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: AIRMAP-DB
      schema: airmap
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.113.135.40:6319/kma_gtad?useUnicode=yes&characterEncoding=UTF-8
    username: kma
    password: kma9633!!

  jpa.hibernate.ddl-auto: none
  jpa.properties.hibernate.jdbc.time_zone : Asia/Seoul
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: false
  jpa.properties.hibernate.format_sql: false
  jackson.default-property-inclusion: NON_NULL
  datasource.validationQuery: SELECT 1

  mybatis:
    config-location: classpath:config/mybatis-config.xml
    mapper-locations:
      - mapper/**/*.xml